### ISSUE TITLE
Duration of event is shorter then the timer for the meteor

### ISSUE THREAD

**Issue by Mirzoda** [emipa606/YayosMeteor#3]
Talking about the [TryExecuteWorker](https://github.com/emipa606/YayosMeteor/blob/main/Source/MeteorIncident/IncidentWorker_MeteorStormCondition.cs) method:
Even when triggering the event in the development mode, the meteor never came. The event ended without anything happening.
I added some logging and tried figuring out what was happening.

I came to the conclusion that the duration is shorter than the GameCondition_MeteorStorm.nextMeteorTicks resulting in the event ending before generating/triggering the Meteor. I'm not familiar with Rim World modding and don't fully understand the flow of everything, but when I added a simple if
`
if (duration < GameCondition_MeteorStorm.nextMeteorTicks)
{
    duration = GameCondition_MeteorStorm.nextMeteorTicks;
}
`
then at least the meteor dropped out of the sky. Hence my conclusion.

Numbers when delay was set to 1 second and 2 seconds respectively.
![image](https://github.com/emipa606/YayosMeteor/assets/19552723/2dc3d20c-e9df-4a6c-9040-2ffbaeaad896)

**Comment by Mirzoda** [comment]
I added the logging here:
![image](https://github.com/emipa606/YayosMeteor/assets/19552723/cbad087f-59ed-4df6-9334-677d2e3c4d06)

**Comment by emipa606** [comment]
Nice catch, should be fixed in 265e151
Seems the threat-scale could affect the time until the first impact to be greater than the duration as you noticed.
This should now be clamped below the max-duration regardless of the current threat-scale.

**Comment by Mirzoda** [comment]
Thanks for the quick response!
